// <auto-generated />
using GraphQL_example.Domain.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GraphQL_example.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220616171527_Add Seed data")]
    partial class AddSeeddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("GraphQL_example.Domain.Models.ItemData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Done")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ListId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ListId");

                    b.ToTable("ItemData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Hahahahah",
                            Done = false,
                            ListId = 1,
                            Title = "Testing data 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Second one",
                            Done = true,
                            ListId = 1,
                            Title = "Testing data 2"
                        });
                });

            modelBuilder.Entity("GraphQL_example.Domain.Models.ItemList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ItemList");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "To do list"
                        });
                });

            modelBuilder.Entity("GraphQL_example.Domain.Models.ItemData", b =>
                {
                    b.HasOne("GraphQL_example.Domain.Models.ItemList", "ItemList")
                        .WithMany("ItemDatas")
                        .HasForeignKey("ListId")
                        .HasConstraintName("FK_ItemData_ItemList")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemList");
                });

            modelBuilder.Entity("GraphQL_example.Domain.Models.ItemList", b =>
                {
                    b.Navigation("ItemDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
